name: Verilator Simulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verilate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Verilator dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator make g++ pkg-config

    - name: Run Verilator build
      run: |
        verilator -CFLAGS -fcoroutines \
                  --cc --main --build --exe --timing --trace \
                  -Wno-fatal \
                  --top-module tb_can_top \
                  SIM/*.v RTL/*.v
    
    - name: Run Verilator simulation
      run: |
        ./obj_dir/Vtb_can_top
